from settings import COLLECTOR, TRAINER, ANALYZER, COLLECTOR_SPECIFICATIONS, TRAINER_SPECIFICATIONS, ANALYZER_SPECIFICATIONS

# TODO implement cli options
COLLECTOR(**COLLECTOR_SPECIFICATIONS).run()
TRAINER(**TRAINER_SPECIFICATIONS).run()
ANALYZER(**ANALYZER_SPECIFICATIONS).run()